### ISSUE TITLE
Does this support Simple Authentication?

### ISSUE THREAD

**Issue by gibman62** [cyga/www_fdw#23]
Great utility BTW. Trying to authenticate against an https web server to dish out some xml - can you advise if/how it can be done? I have tried the conventional curl stuff, but with no success.

**Comment by cyga** [comment]
Thanks.

Authentication can be a complex process.
I think best option is to have server in the middle, which will process auth and serve as a proxy.

From the other point, if there are some options (like api key for example), you can add it with www_fdw callbacks.

**Comment by gibman62** [comment]
Many thanks Alex, hadn't thought of a proxy - good idea!
