### ISSUE TITLE
Doesn't compile against PostgreSQL 9.6 beta3

### ISSUE THREAD

**Issue by robe2** [cyga/www_fdw#29]
I could be mistaken, but doesn't look like the code has been updated to support 9.6 changes.
I'll take a crack at fixing and submit a pull request if I figure it out.

This is what I get for errors

> src/www_fdw.c: In function 'www_get_foreign_paths':
src/www_fdw.c:644:38: error: incompatible type for argument 3 of 'create_foreignscan_path'
                                      )); /* no fdw_private data */
                                      ^
In file included from src/www_fdw.c:20:0:
C:/MING64~1/projects/POSTGR~1/rel/PG9~2.6W6/include/server/optimizer/pathnode.h:90:21: note: expected 'struct PathTarget *' but argument is of type 'double'
 extern ForeignPath *create_foreignscan_path(PlannerInfo *root, RelOptInfo *rel,
                     ^
src/www_fdw.c:644:38: error: incompatible type for argument 6 of 'create_foreignscan_path'
                                      )); /* no fdw_private data */
                                      ^
In file included from src/www_fdw.c:20:0:
C:/MING64~1/projects/POSTGR~1/rel/PG9~2.6W6/include/server/optimizer/pathnode.h:90:21: note: expected 'Cost' but argument is of type 'struct List *'
 extern ForeignPath *create_foreignscan_path(PlannerInfo *root, RelOptInfo *rel,
                     ^
src/www_fdw.c:644:38: warning: passing argument 9 of 'create_foreignscan_path' from incompatible pointer type [enabled by default]
                                      )); /* no fdw_private data */
                                      ^
In file included from src/www_fdw.c:20:0:
C:/MING64~1/projects/POSTGR~1/rel/PG9~2.6W6/include/server/optimizer/pathnode.h:90:21: note: expected 'struct Path *' but argument is of type 'struct List *'
 extern ForeignPath *create_foreignscan_path(PlannerInfo *root, RelOptInfo *rel,
                     ^
src/www_fdw.c:644:38: error: too few arguments to function 'create_foreignscan_path'
                                      )); /* no fdw_private data */
                                      ^
In file included from src/www_fdw.c:20:0:
C:/MING64~1/projects/POSTGR~1/rel/PG9~2.6W6/include/server/optimizer/pathnode.h:90:21: note: declared here
 extern ForeignPath *create_foreignscan_path(PlannerInfo *root, RelOptInfo *rel,
                     ^
src/www_fdw.c: In function 'serialize_request_with_callback':
src/www_fdw.c:852:9: warning: format '%i' expects argument of type 'int', but argument 3 has type 'uint64' [-Wformat=]
         ereport(ERROR,
         ^
src/www_fdw.c:862:9: warning: format '%i' expects argument of type 'int', but argument 3 has type 'uint64' [-Wformat=]
         ereport(ERROR,
         ^
src/www_fdw.c: In function 'get_www_fdw_options':
src/www_fdw.c:1459:9: warning: format '%d' expects argument of type 'int', but argument 2 has type 'uint64' [-Wformat=]
         ereport(ERROR,
         ^
src/www_fdw.c: In function 'get_www_fdw_post_parameters':
src/www_fdw.c:1526:9: warning: format '%d' expects argument of type 'int', but argument 2 has type 'uint64' [-Wformat=]
         ereport(ERROR,
         ^
src/www_fdw.c: In function 'call_response_iterate_callback':
src/www_fdw.c:2016:9: warning: format '%i' expects argument of type 'int', but argument 3 has type 'uint64' [-Wformat=]
         ereport(ERROR,
         ^
src/www_fdw.c: At top level:
src/www_fdw.c:167:13: warning: 'www_explain_foreign_scan' declared 'static' but never defined [-Wunused-function]
 static void www_explain_foreign_scan(ForeignScanState *node, ExplainState *es);^

**Comment by cyga** [comment]
> I'll take a crack at fixing and submit a pull request if I figure it out.

ok

**Comment by robe2** [comment]
I got it to compile and can install but is crashing.  I suspect it might be related to:

warning: format '%i' expects argument of type 'int', but argument 3 has type 'uint64' [-Wformat=]

Which only shows when I compile against 9.6beta3.  So working to fix that before I push a pull request.

**Comment by cyga** [comment]
has to be fixed after merge with patch.
