### ISSUE TITLE
Are File Headers Required for CSV?

### ISSUE THREAD

**Issue by paprockiw** [cyga/www_fdw#31]
I have a large csv file that I'm trying to load and it only processes the first line of the file. The file has no headers, and I haven't seen anything in the documentation about headers. Are headers required to load a csv file?

**Comment by cyga** [comment]
@paprockiw I don't understand your question.

Why do you think www-fdw has to deal with csv files? Did you read about it in docs/examples?
https://github.com/cyga/www_fdw/wiki

**Comment by paprockiw** [comment]
Ha! I'm sorry, wrong project. And I ended up answering my own question for that other projecct anyway.
