### ISSUE TITLE
Web API requiring authentication

### ISSUE THREAD

**Issue by ishraqiyun77** [cyga/www_fdw#35]
Hi, more of a question than an issue.

`www_fdw` sounded like the solution to what I needed, but unfortunately the Web API requires authorization.  Is there a way to `www_fdw` and add authorization credentials to it?

The company I work for uses Microsoft Dynamics CRM 365 which is web-based, so we don't have access to the database directly. It has a Web API that is pretty well documented and works well. However, getting data out of it efficiently has been an issue. Something like `www_fdw` would be the most desirable/efficient solution.

**Comment by cyga** [comment]
@ishraqiyun77 I suppose the best option here is create proxy server which do authorization with your server and provides data. May be even converts for better auto parse/convertion of  www_fdw.

You can specify this proxy in configuration then. It's mentioned in docs https://github.com/cyga/www_fdw/wiki/Documentation. But there is no example on it.

**Comment by ishraqiyun77** [comment]
Got it! I'll look into it further.

Also, sorry I noticed after the fact someone had asked basically the same question here: #23.
